<?php

use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $skillSeeder = [
            ['student_login_id' => 'st01', 'language_code'=> 1, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st01', 'language_code'=> 4, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 5, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 6, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 7, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 9, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st01', 'language_code'=> 13, 'language_level_code'=> 2],
            ['student_login_id' => 'st01', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st01', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st01', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st02', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st02', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st02', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st02', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st02', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st02', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st02', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st02', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st02', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st02', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st02', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st02', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st02', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st02', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st02', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st03', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st03', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st03', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st03', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st03', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st03', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st03', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st03', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st03', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st03', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st03', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st03', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st03', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st03', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st03', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st03', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st03', 'language_code'=> 17, 'language_level_code'=> 2],
            ['student_login_id' => 'st04', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st04', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st04', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st04', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st04', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st04', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st04', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st04', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st04', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st04', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st04', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st04', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st04', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st04', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st04', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st04', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st04', 'language_code'=> 17, 'language_level_code'=> 2],
            ['student_login_id' => 'st05', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st05', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st05', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st05', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st05', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st05', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st05', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st05', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st05', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st05', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st05', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st05', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st05', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st05', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st05', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st05', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st05', 'language_code'=> 17, 'language_level_code'=> 2],
            //
            ['student_login_id' => 'st06', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st06', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st06', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st06', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st06', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st06', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st06', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st06', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st06', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st06', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st06', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st06', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st06', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st06', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st06', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st06', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st06', 'language_code'=> 17, 'language_level_code'=> 2],
            //
            ['student_login_id' => 'st07', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st07', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st07', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st07', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st07', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st07', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st07', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st07', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st07', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st07', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st07', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st07', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st07', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st07', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st07', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st07', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st07', 'language_code'=> 17, 'language_level_code'=> 2],
            //
            ['student_login_id' => 'st08', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st08', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st08', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st08', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st08', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st08', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st08', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st08', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st08', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st08', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st08', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st08', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st08', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st08', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st08', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st08', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st08', 'language_code'=> 17, 'language_level_code'=> 2],
            //
            ['student_login_id' => 'st09', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st09', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st09', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st09', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st09', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st09', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st09', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st09', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st09', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st09', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st09', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st09', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st09', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st09', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st09', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st09', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st09', 'language_code'=> 17, 'language_level_code'=> 2],
            //
            ['student_login_id' => 'st10', 'language_code'=> 1, 'language_level_code'=> 3],
            ['student_login_id' => 'st10', 'language_code'=> 2, 'language_level_code'=> 2],
            ['student_login_id' => 'st10', 'language_code'=> 3, 'language_level_code'=> 2],
            ['student_login_id' => 'st10', 'language_code'=> 4, 'language_level_code'=> 4],
            ['student_login_id' => 'st10', 'language_code'=> 5, 'language_level_code'=> 5],
            ['student_login_id' => 'st10', 'language_code'=> 6, 'language_level_code'=> 2],
            ['student_login_id' => 'st10', 'language_code'=> 7, 'language_level_code'=> 3],
            ['student_login_id' => 'st10', 'language_code'=> 8, 'language_level_code'=> 1],
            ['student_login_id' => 'st10', 'language_code'=> 9, 'language_level_code'=> 4],
            ['student_login_id' => 'st10', 'language_code'=> 10, 'language_level_code'=> 1],
            ['student_login_id' => 'st10', 'language_code'=> 11, 'language_level_code'=> 1],
            ['student_login_id' => 'st10', 'language_code'=> 12, 'language_level_code'=> 1],
            ['student_login_id' => 'st10', 'language_code'=> 13, 'language_level_code'=> 3],
            ['student_login_id' => 'st10', 'language_code'=> 14, 'language_level_code'=> 4],
            ['student_login_id' => 'st10', 'language_code'=> 15, 'language_level_code'=> 3],
            ['student_login_id' => 'st10', 'language_code'=> 16, 'language_level_code'=> 2],
            ['student_login_id' => 'st10', 'language_code'=> 17, 'language_level_code'=> 2],
        ];

        foreach($skillSeeder as $skillSeeders) {
            DB::table('skills')->insert([
                'student_login_id' => $skillSeeders['student_login_id'],
                'language_code' => $skillSeeders['language_code'],
                'language_level_code' => $skillSeeders['language_level_code'],
            ]);
        }
    }
}
